### PR TITLE
Added gunicorn

### PR DESCRIPTION
**Pull request by Hum4n01d**
I works now [check it out](https://pollute-a-meter-test.herokuapp.com)

### CODE REVIEW

**Comment by AtomicCreeper** [comment]
wonderful. you do have pull/push privileges on the main repo, yes?

**Comment by Hum4n01d** [comment]
Nope :D

**Comment by AtomicCreeper** [comment]
Welcome to the repo. Sorry about that!

**Comment by Hum4n01d** [comment]
Great!

**Comment by Hum4n01d** [comment]
Thanks!

**Comment by Hum4n01d** [comment]
Can I delete the venv folders? They’re causing a problem

**Pull request merged**
